### ISSUE TITLE
404 link

### ISSUE THREAD

**Issue by MikiP98** [null511/PixelGraph#11]
On the wiki page [`https://github.com/Null-MC/PixelGraph/wiki/Installation`](https://github.com/Null-MC/PixelGraph/wiki/Installation), there is a link to non existent page [`https://github.com/null511/MC-PBR-Pipeline/releases`](https://github.com/null511/MC-PBR-Pipeline/releases) instead of [`https://github.com/Null-MC/PixelGraph/releases`](https://github.com/Null-MC/PixelGraph/releases)

**Comment by null511** [comment]
fixed, thanks.
